### ISSUE TITLE
Error: Unable to update Callisto (callisto-theme.yaml) 

### ISSUE THREAD

**Issue by ghost** [iganeshk/standardnotes-extensions#22]
Please  Can help they start do right way till callisto-theme.yaml Please fix  this thanks so much

python3 build_repo.py
Unknown error occurred: 'status'
Extension: ActionBar                      1.3.2         (updated)
Extension: Quick Tags                     1.3.2         (updated)
Extension: Bold Editor                    1.2.2         (updated)
Extension: Code Editor                    1.3.8         (updated)
Extension: Folders Component              1.3.8         (updated)
Extension: GitHub Push                    1.2.4         (updated)
Extension: Simple Markdown Editor         1.4.0         (updated)
Extension: Markdown Pro                   1.3.14        (updated)
Extension: Math Editor                    1.3.4         (updated)
Extension: 2FA Manager                    1.2.5         (updated)
Extension: Minimal Markdown Editor        1.3.7         (updated)
Extension: Plus Editor                    1.5.0         (updated)
Extension: Rich Markdown Editor           0.18.0        (updated)
Extension: Secure Spreadsheets            1.4.0         (updated)
Extension: Simple Task Editor             1.3.7         (updated)
Extension: TokenVault                     2.0.3         (updated)
Extension: Vim Editor                     1.3.7         (updated)
Theme: Autobiography                      1.0.0         (updated)
Error: Unable to update Callisto (callisto-theme.yaml) does it have a release at Github?
Traceback (most recent call last):
  File "build_repo.py", line 283, in <module>
    main()
  File "build_repo.py", line 268, in main
    parse_extensions(base_dir, base_url, ghub_session)
  File "build_repo.py", line 137, in parse_extensions
    ext_yaml = yaml.load(extyaml, Loader=yaml.FullLoader)
  File "/usr/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.8/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/lib/python3.8/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/lib/python3.8/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/lib/python3.8/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/usr/lib/python3.8/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python3.8/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/volume1/docker/standardnotes-extensions/extensions/dark-hybrid-theme.yaml", line 2, column 3

**Comment by irmantask** [comment]
having a same issue

**Comment by xthursdayx** [comment]
I'll check it out. It's working for me, but I'll recheck the download link and `yaml` in the morning and update if necessary. Sorry about that. Please check back some time later tomorrow, and hopefully I'll have fixed the issue. I'll post any updates here. Cheers.

**Comment by xthursdayx** [comment]
@irmantask I figured out what the problem is. 

The problem seems to come from the way that the `build_repo.py` script is processing GitHub repos that don't have tagged releases. I don't really know Python, but after reading the script, it seems like the issues is that `build_repo.py` grabs the theme and extension repos either via a GitHub session if they have a tagged release, using the `process_zipball` function and the `release version` variable, or by the `git_clone_method` function, which relies on the `ext_version` variable.  This variable (`ext_version`) still relies on the repo having tags or on `ext_last_commit`, which, despite seeming to denote the last commit (not release or tag), also relies on the repo having `refs/tags` in its `rev-list`. See the section of code here: 
```
def git_clone_method(ext_yaml, public_dir, ext_has_update):
    """
    Get the latest repository and parse for metadata
    """
    repo_name = ext_yaml['github'].split('/')[-1]
    repo_dir = os.path.join(public_dir, repo_name)
    run([
        'git', 'clone', 'https://github.com/{github}.git'.format(**ext_yaml),
        '--quiet', '{}_tmp'.format(repo_name)
    ],
        check=True)
    ext_last_commit = (run([
        'git', '--git-dir=' +
        os.path.join(public_dir, '{}_tmp'.format(repo_name), '.git'),
        'rev-list', '--tags', '--max-count=1'
    ],
                           stdout=PIPE,
                           check=True).stdout.decode('utf-8').replace(
                               "\n", ""))
    ext_version = run([
        'git', '--git-dir',
        os.path.join(public_dir, '{}_tmp'.format(repo_name), '.git'),
        'describe', '--tags', ext_last_commit
    ],
                      stdout=PIPE,
                      check=True).stdout.decode('utf-8').replace("\n", "")
```
The key `parse_extensions` function, which builds the Standard Notes extensions repository using GitHub metadata, seems to be where the major problems arise, since this function also relies on repo tags or releases due to the following code:
```
# If we don't have a Github API Session, do git-clone instead
if ghub_session is not None:
    # Get extension's github release meta-data
    ext_git_info = json.loads(
             ghub_session.get(
                        'https://api.github.com/repos/{github}/releases/latest'.
                        format(**ext_yaml)).text)
    try:
           ext_version = ext_git_info['tag_name']
    except KeyError:
             # No release's found
            print(
                    "Error: Unable to update %s (%s) does it have a release at Github?"
                    % (ext_yaml['name'], extfile))
```

The issues seems to be that some people choose to publish their themes to [https://listed.to](https://listed.to) instead of creating Github releases. In those cases there may or may not be any releases on Github or any tags, but either way, there is a good chance that if there are they're out of date with the actual repo and theme css itself. Of course, it is possible for Standard Notes end users to add these themes themselves via the `Import Extensions` button in Standard Notes, using the `listed.to` link, for example [https://listed.to/p/u0KtH2x98F](https://listed.to/p/u0KtH2x98F ) for ilindaniel's Evernote Dark theme.

One way this might be solved is by adding including a `download_url` line in the theme and extension `yaml` files and having the `build_repo.py` script parse this line if no tagged releases exist on GitHub, This would be easy enough to implement since most of the themes that lack proper release do have `download_url` links listed somewhere in their repo. For example, to continue using ilindaniel's Evernote Dark theme repo as an example, his `ext.json` includes the line `"download_url": "https://github.com/ilindaniel/sn-theme-evernote-dark/archive/master.zip"`, much like Lissy93 included the `download_url` `https://github.com/Lissy93/callisto-theme-standard-notes/archive/refs/heads/master.zip` in the `callisto-theme.json` file in their repo.

Right now, the `build-repo.py` script does include the `download_url` variable  in the `parse_extensions` function, however it is in this format: ` download_url='https://github.com/{}/archive/{}.zip'.format(ext_yaml['github'], ext_version),`, which again seems to rely on a release version and is not the same `download_url` format used by each theme repo.

I don't know enough about Python to know how to modify the `build_repo.py` script to differentiate between repos with tagged releases and those without, and to process the latter using their `download_url`, so unfortunately I can't submit a PR to address this, and I'm not sure if it's something you want to take on @irmantask, but that seems to be the best way to include the additional themes in this repo without users having to add them individually.

**Comment by gyaneesh** [comment]
> @irmantask I figured out what the problem is.
> The issues seems to be that some people choose to publish their themes to https://listed.to instead of creating Github releases. In those cases there may or may not be any releases on Github or any tags, but either way, there is a good chance that if there are they're out of date with the actual repo and theme css itself. Of course, it is possible for Standard Notes end users to add these themes themselves via the `Import Extensions` button in Standard Notes, using the `listed.to` link, for example https://listed.to/p/u0KtH2x98F for ilindaniel's Evernote Dark theme.

You've got the analysis right but like you've figured, only relying on releases at github since having a release with tag would be convenient to differentiate releases. While the code can be adapted to grab the branch but it wouldn't be a good practice, Best bet would be to request a release from the publisher. Let me know if this sounds good.

**Comment by xthursdayx** [comment]
Works for me. My original intention with the PR was just to centralize all the existing themes and extensions in this one repo, but it makes sense to continue relying on release tags. There are a couple of other themes causing issues for the same reason the Callisto one was, so I'll create a new PR to remove them. I'll also consider following up with the publishers to see if they're willing to tag a GH release and if they are, I'll add them back in at a later date.

**Comment by xthursdayx** [comment]
This can be closed. I requested tagged releases from all of the theme maintainers included in my recent PR (including Callisto), and forked the repos that I didn't hear back from in order to create my own tagged releases.
