### ISSUE TITLE
Installation and integration in standard notes

### ISSUE THREAD

**Issue by paoloha** [iganeshk/standardnotes-extensions#4]
Hi,
I was wondering if i still need the extended/payed version to use the extensions.
I followed your instructions but i don't get new extensions in standardnotes..

Thanks for any help.

**Comment by vsrmdev** [comment]
It worked for me so you're doing something wrong. The problem I had was not inputting the proper URL on StandardNotes so that might be your issue. When you enter the code for the extensions you must add "/extensions/index.json" after the URL, otherwise you won't see any of the extensions. Hope that helped.
