### ISSUE TITLE
no "dist" folder created for simple tastk editor

### ISSUE THREAD

**Issue by Siminon** [iganeshk/standardnotes-extensions#43]
When I do a python3 build_repo.py no dist folder (public/simple-task-editor/1.3.10/dist) is created for the simple tastk editor. The build repo output shows all fine and simple-task-editor 1.3.10 as updated. I also tried it after deleting the previousl public folder.
Therefore it also can't be loaded into standardnotes as https://sample.com/extensions/simple-task-editor/1.3.10/dist/index.html can't be found.
I suspect this happens since the 1.3.10 update, but can't be shure.

By the way thanks for creating this great tool! It does help me alot.

**Comment by xthursdayx** [comment]
Thanks for flagging this. This issue stems from the fact that the Standard Notes devs removed the dist directory from their repo on [May 17th](https://github.com/standardnotes/simple-task-editor/commit/013ac67883bf16e55661846cfd6f0fcfe3bda42c). However, looking into this alerting me to the fact that the SN devs have chosen to pull all of the official extensions into the `standardnotes/app` repo (formerly `standardnotes/web`), rather than maintaining separate repos for each extension. See: https://github.com/standardnotes/app/tree/main/packages/components/src/packages

Unfortunately, this will have far-reaching implications for how the standardnotes-extensions tool pulls the official extensions for self-hosting. @iganeshk I wanted to make sure that you see this issue. Let me know if I can help at all in the process of updating the repo to reflect this change.

**Comment by xthursdayx** [comment]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
Some options for addressing this issue:

Based on the way that `build_repo.py` currently processes github repos, I think that we might be able to use the `git filter-branch` command to pull these specific subdirectories for each official Standard Notes extension. Maybe as part of the `process_zipball` process. However, the downstide is that `standardnotes/app` will be downloaded each time. 

Example:
```
git clone https://github.com/standardnotes/app.git repo_dir (e.g. /extensions/public/simple-task-editor)
cd repo_dir
git filter-branch --prune-empty --subdirectory-filter /packages/components/src/packages/org.standardnotes.simple-task-editor HEAD
```
The only other issue (other than repeatedly downloading the main repo) would be flagging the "official" extensions that exist within the main `standardnotes/app` repo in order to process them using `filter-branch` vs other extensions that exist in their own standalone repositories and will be process the normal way. 

Another option is be to use the [github-clone](https://github.com/HR/github-clone) tool to download each extension subdirectory.

Finally, if we care about keeping the extensions directories synced with the `standardnotes/app` repo `HEAD`, then `git sparse-checkout` may be an option, though I hand/t't used it before. This [stackoverflow answer](https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository/52269934#52269934) suggests using `sparse-checkout` in conjunction with `git clone --filter`:
Example:
```
git clone \
  --depth 1  \
   --filter=tree:0  \
  --sparse \
 https://github.com/standardnotes/app \
 repo_dir (e.g. /extensions/public/simple-task-editor) \
;
cd repo_dir
git sparse-checkout set packages/components/src/packages/org.standardnotes.simple-task-editor
```
I've now tested this method and it appears to work, with the caveat that the  original repo directory structure remains in place, so we would probably want to add a line like `mv /extensions/public/simple-task-editor/packages/components/src/packages/org.standardnotes.simple-task-editor /extensions/public/simple-task-editor/`

See: 
https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/#sparse-checkout-and-partial-clones
&
https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository

One other note: the simplest option may be to use `svn` to copy the subdirectories, as suggested here: https://stackoverflow.com/a/39317180

**Comment by julianfairfax** [comment]
I don't think this has been fixed bot
